security:
    password_hashers:
        Symfony\Component\Security\Core\User\UserInterface: 'plaintext'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: login

    firewalls:
        api:
            stateless: true
            custom_authenticators:
                - App\Security\BearerAuthenticator
            entry_point: App\Security\BearerAuthenticator

    access_control:
        - { path: ^/v1/api/users, roles: IS_AUTHENTICATED_FULLY }
